use_frameworks!

platform :ios, '9.0'

target 'CocoaPods_PrivateResposition_demo_Example' do
  pod 'CocoaPods_PrivateResposition_demo', :path => '../'

  target 'CocoaPods_PrivateResposition_demo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
